### ISSUE TITLE
Redirect configs in child routers don't work

### ISSUE THREAD

**Issue by bastienJS** [aurelia/router#103]
The router does not write the "Welcome" into the URL.

The angularjs router has the same "design flaw".

Can this be fixed?

My expectation is to get a correct URL for default routes. Also for the initial root route.

![image](https://cloud.githubusercontent.com/assets/5945955/7783318/cf42f1c6-013e-11e5-8213-2772c67001fd.png)

**Comment by bryanrsmith** [comment]
I'm not sure what you mean.

Do you want the router's nav links to use `'welcome'` instead of `''`? It uses the first pattern in the route array, so you can specify `route: [ 'welcome', '' ]` to accomplish that.

Do you want the default route `''` to redirect to `'welcome'`? You can do that by adding a redirect route instead of making `''` an alias for `'welcome'`: `{ route: '', redirect: 'welcome' }`. It does look like we might have a problem with redirects in child routers. I will create a separate case for that bug & try to look into it soon.

**Comment by BlueHayes** [comment]
I believe the redirect setup is the correct way to resolve this. However I'm having issues with redirects in child routers as @bryanrsmith mentions, good to hear that's already been picked up on though.

**Comment by bastienJS** [comment]
@bryanrsmith  I can confirm what @BlueHayes said:

The redirect does not work in child router see here:

http://plnkr.co/edit/XOBJn3?p=preview

check the browser for error in console

TypeError: Illegal module name ""
    at x.$__Object$defineProperty.value (https://jspm.io/es6-module-loader@0.16.5.js:1:29223)
    at x.$__global.upgradeSystemLoader.e.normalize (https://jspm.io/system@0.16.7.js:5:16986)
    at x.$__global.upgradeSystemLoader.e.normalize (https://jspm.io/system@0.16.7.js:5:17338)
    at x.$__global.upgradeSystemLoader.e.normalize (https://jspm.io/system@0.16.7.js:5:21688)
    at n.execute.n.loadModule (https://cdn.rawgit.com/distros/aurelia/0.13.0/aurelia.js:5:1115)
    at execute.e.importViewModelResource (https://cdn.rawgit.com/distros/aurelia/0.13.0/aurelia.js:9:2763)
    at execute.e.createViewModel (https://cdn.rawgit.com/distros/aurelia/0.13.0/aurelia.js:8:2850)
    at r.execute.c.loadRoute (https://cdn.rawgit.com/distros/aurelia/0.13.0/aurelia.js:11:782)
    at i (https://cdn.rawgit.com/distros/aurelia/0.13.0/aurelia.js:9:31513)
    at r (https://cdn.rawgit.com/distros/aurelia/0.13.0/aurelia.js:9:30990)(anonymous function) @ aurelia.js:10r @ aurelia.js:4(anonymous function) @ aurelia.js:4t.exports @ aurelia.js:1j.(anonymous function) @ aurelia.js:4n @ aurelia.js:4r @ aurelia.js:4

**Comment by bastienJS** [comment]
and I correct my harsh comment. The root redirect works, but I couldnt make it work in angular :P
