### ISSUE TITLE
Transient 'Route not found' on various routes throughout my app

### ISSUE THREAD

**Issue by Zensavona** [aurelia/router#193]
Hi guys, I've been struggling with this for a while now through various router versions and have had little luck trying to debug it. 

I'm getting a 'Error: Route not found (route)' on various routes, only very transiently (maybe 1 in every 15 pageloads) and only on the initial page load. 

Here's an example output from the main route of the root router:

```
DEBUG [aurelia] Loading plugin github:aurelia/templating-binding@0.14.0.
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin github:aurelia/templating-binding@0.14.0.
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin github:aurelia/templating-resources@0.14.0.
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin github:aurelia/templating-resources@0.14.0.
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin github:aurelia/history-browser@0.7.0.
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin github:aurelia/history-browser@0.7.0.
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin github:aurelia/templating-router@0.15.0.
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin github:aurelia/templating-router@0.15.0.
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin github:aurelia/event-aggregator@0.7.0.
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin github:aurelia/event-aggregator@0.7.0.
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:46 INFO [aurelia] Aurelia Started
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [templating] importing resources for app.html Array[0]
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:62 ERROR [app-router] Error: Route not found: /
    at AppRouter.createNavigationInstruction (http://localhost:3000/assets/jspm_packages/github/aurelia/router@0.11.0/aurelia-router.js:1405:29)
    at AppRouter.loadUrl (http://localhost:3000/assets/jspm_packages/github/aurelia/router@0.11.0/aurelia-router.js:1502:19)
    at BrowserHistory.loadUrl (http://localhost:3000/assets/jspm_packages/github/aurelia/history-browser@0.7.0/aurelia-history-browser.js:153:55)
    at BrowserHistory.activate (http://localhost:3000/assets/jspm_packages/github/aurelia/history-browser@0.7.0/aurelia-history-browser.js:116:21)
    at AppRouter.activate (http://localhost:3000/assets/jspm_packages/github/aurelia/router@0.11.0/aurelia-router.js:1611:20)
    at AppRouter.registerViewPort (http://localhost:3000/assets/jspm_packages/github/aurelia/router@0.11.0/aurelia-router.js:1579:16)
    at new RouterView (http://localhost:3000/assets/jspm_packages/github/aurelia/templating-router@0.15.0/router-view.js:17:19)
    at Object.construct (http://localhost:3000/assets/jspm_packages/npm/core-js@0.9.18/modules/es6.reflect.js:47:25)
    at ClassActivator.invoke (http://localhost:3000/assets/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:186:22)
    at Container.invoke (http://localhost:3000/assets/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:399:31)error @ :3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:62
:3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:62 ERROR [app-router] Router navigation failed, and no previous location could be restored.error @ :3000/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:62
```

And here's my router:

```
@inject(WebAPI)
export class App {
  constructor(api) {
    this.api = api;
  }

  activate() {
    this.api.getCurrentUser().then(u => {
      this.user = u;
      this.configureRouter = this.sexyRouterConfiguration;
    });
  }

  sexyRouterConfiguration(config, router) {
    config.title = 'Welcome 🔥';

    config.addPipelineStep('authorize', AuthorizeStep);
    config.map([
      { route: ['','sites'], moduleId: 'sites/sites', nav: true, title: 'View Sites' },
      { route: ['account'], moduleId: 'account/account', nav: true, title: 'Account' },
      { route: ['invitation-codes'], moduleId: 'invitation-codes', nav: true, title: 'Invitation Codes' },
      { route: ['admin'], moduleId: 'admin/admin', title: 'Administration', auth: true }
    ]);

    this.router = router;
  }
}
```
FWIW I have tried removing both the `config.addPipelineStep` and setting `configureRouter` directly on the `App` class but neither of these things fix the error, so I left these complications in the example for the sake of completeness.

I'm pretty confused as I have another Aurelia app with a pretty similar configuration and version/s and I have never seen this error outside of this particular app. Any clues/tips on how to debug this?

Thanks!

**Comment by bryanrsmith** [comment]
Can you still reproduce the error if you return the promise from activate()?

**Comment by Zensavona** [comment]
@brianrsmith As noted above I can reproduce the error with only this code:

```
export class App {
  configureRouter(config, router) {
    config.title = 'Welcome 🔥';

    config.map([
      { route: ['','sites'], moduleId: 'sites/sites', nav: true, title: 'View Sites' },
      { route: ['account'], moduleId: 'account/account', nav: true, title: 'Account' },
      { route: ['invitation-codes'], moduleId: 'invitation-codes', nav: true, title: 'Invitation Codes' },
      { route: ['admin'], moduleId: 'admin/admin', title: 'Administration', auth: true }
    ]);

    this.router = router;
  }
}

**Comment by Zensavona** [comment]
I'll try to reproduce this for you in a plunkr this afternoon

**Comment by Zensavona** [comment]
I'm having a hard time replicating this because of it's transient nature. do you have any ideas as to what might be going on here @bryanrsmith?

Today I further simplified the router in question's VM:

```
import {inject} from 'aurelia-framework';
import {Redirect} from 'aurelia-router';
import {Permissions} from 'permissions';
import {WebAPI} from 'web-api';
import 'semantic-ui-css/semantic.css!';
import 'semantic-ui-css/semantic';

@inject(WebAPI)
export class App {
  constructor(api) {
    this.api = api;
    this.admin = false;
  }

  configureRouter(config, router) {
    config.title = 'NicheBuzz 🔥';

    // config.addPipelineStep('authorize', AuthorizeStep);
    config.map([
      { route: ['','sites'], moduleId: 'sites/sites', nav: true, title: 'View Sites' },
      { route: ['account'], moduleId: 'account/account', nav: true, title: 'Account' },
      { route: ['invitation-codes'], moduleId: 'invitation-codes', nav: true, title: 'Invitation Codes' },
      { route: ['admin'], moduleId: 'admin/admin', title: 'Administration' }
    ]);

    this.router = router;
  }
}
```
and bumped all my Aurelia versions up to the latest ones, still getting these errors pop up.

Here's an error log from today:
```
DEBUG [aurelia] Loading plugin https://niche.buzz/assets/jspm_packages/github/aurelia/templating-binding@0.14.0.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin https://niche.buzz/assets/jspm_packages/github/aurelia/templating-binding@0.14.0.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin https://niche.buzz/assets/jspm_packages/github/aurelia/templating-resources@0.14.0.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin https://niche.buzz/assets/jspm_packages/github/aurelia/templating-resources@0.14.0.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin https://niche.buzz/assets/jspm_packages/github/aurelia/history-browser@0.7.0.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin https://niche.buzz/assets/jspm_packages/github/aurelia/history-browser@0.7.0.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin https://niche.buzz/assets/jspm_packages/github/aurelia/templating-router@0.15.0.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin https://niche.buzz/assets/jspm_packages/github/aurelia/templating-router@0.15.0.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin https://niche.buzz/assets/jspm_packages/github/aurelia/event-aggregator@0.7.0.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin https://niche.buzz/assets/jspm_packages/github/aurelia/event-aggregator@0.7.0.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin aurelia-animator-css.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin aurelia-animator-css.
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:46 INFO [aurelia] Aurelia Started
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:38 DEBUG [templating] importing resources for app.html Array[0]
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:62 ERROR [app-router] Error: Route not found: /
    at AppRouter.createNavigationInstruction (https://niche.buzz/assets/jspm_packages/github/aurelia/router@0.11.0/aurelia-router.js:1405:29)
    at AppRouter.loadUrl (https://niche.buzz/assets/jspm_packages/github/aurelia/router@0.11.0/aurelia-router.js:1502:19)
    at BrowserHistory.loadUrl (https://niche.buzz/assets/jspm_packages/github/aurelia/history-browser@0.7.0/aurelia-history-browser.js:153:55)
    at BrowserHistory.activate (https://niche.buzz/assets/jspm_packages/github/aurelia/history-browser@0.7.0/aurelia-history-browser.js:116:21)
    at AppRouter.activate (https://niche.buzz/assets/jspm_packages/github/aurelia/router@0.11.0/aurelia-router.js:1611:20)
    at AppRouter.registerViewPort (https://niche.buzz/assets/jspm_packages/github/aurelia/router@0.11.0/aurelia-router.js:1579:16)
    at new RouterView (https://niche.buzz/assets/jspm_packages/github/aurelia/templating-router@0.15.0/router-view.js:17:19)
    at Object.construct (https://niche.buzz/assets/jspm_packages/npm/core-js@0.9.18/modules/es6.reflect.js:47:25)
    at ClassActivator.invoke (https://niche.buzz/assets/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:186:22)
    at Container.invoke (https://niche.buzz/assets/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:399:31)error @ /assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:62
/assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:62 ERROR [app-router] Router navigation failed, and no previous location could be restored.error @ /assets/jspm_packages/github/aurelia/logging-console@0.6.2/aurelia-logging-console.js:62
```

Tearing my hair out about this a bit...

**Comment by EisenbergEffect** [comment]
@Zensavona Can you create a bare minimum reproduction of the issue and zip it up? If we can reproduce it ourselves, that makes everything much easier. If it's a bug we can fix it or if it's something else, then we can at least provide some better error information. At this point, it's hard to see what is going wrong.

**Comment by bryanrsmith** [comment]
@Zensavona Are you still seeing this problem? We'd love to help but I think we'll need a complete repro in a plunker or a zip of your app.

**Comment by Zensavona** [comment]
Yup, I'll try to get around to it tomorrow - it's related to a side project that I haven't touched in a while now.

Thanks!

**Comment by EisenbergEffect** [comment]
Haven't heard back in a while so I assume it's no longer an issue. This was likely a combination of the module loader with the route configuration module ids.
