### ISSUE TITLE
app-router error when mapUnknownRoutes is called

### ISSUE THREAD

**Issue by TomSelleck** [aurelia/router#283]
When the following method is added to the router, an error is thrown in the console when a user navigates to an unknown route:
```
export class App {
  configureRouter(config, router) {
    config.title = 'Aurelia';
    config.map([
      { route: ['', 'welcome'], name: 'welcome',      moduleId: 'welcome',      nav: true, title: 'Welcome' },
      { route: 'users',         name: 'users',        moduleId: 'users',        nav: true, title: 'Github Users' },
      { route: 'test',         name: 'test',        moduleId: 'test',        nav: true, title: 'Test Page' }
    ]);
	
	config.mapUnknownRoutes(instruction => {
		console.log("debug config.mapUnknownRoutes message");
		router.navigate("welcome");
	});

    this.router = router;
  }
}
```

If I navigate to `http://localhost:9000/#/users` and then enter the url as `http://localhost:9000/#/users2` and press return, I get the following error in the console:

```
debug config.mapUnknownRoutes message
ERROR [app-router] TypeError: Cannot set property 'route' of undefined
    at http://localhost:9000/jspm_packages/npm/aurelia-router@1.0.0-beta.1.0.1/aurelia-router.js:1011:17
    at h (http://localhost:9000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1773:66)
    at http://localhost:9000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1778:19
    at MutationObserver.e (http://localhost:9000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1958:55)
```

The app behaves as expected, navigating to `welcome`.

**Comment by TomSelleck** [comment]
Issue is with my code, not the router.

This
```
    config.mapUnknownRoutes(instruction => {
        console.log("debug config.mapUnknownRoutes message");
        router.navigate("welcome");
    });
```

Should be:
```
        config.mapUnknownRoutes(instruction => {
            console.log("config.mapUnknownRoutes");
            return "login";
        });
```
