### ISSUE TITLE
Refreshing In A Child Router Shouldn't Prevent Normally Working Routes From Being Found

### ISSUE THREAD

**Issue by robbert229** [aurelia/router#441]
**I'm submitting a bug report**

* **Library Version:**
1.0.7

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
4.0.2

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.27

* **Browser:**
all
* **Language:**
ESNext

**Current behavior:**

When I reload a page while in a child router's child router the routes are not found even though if I load the page from the root the routes are found normally.

**Expected/desired behavior:**

[Gist](https://gist.run/?id=81807772f680770e15e6312ca36cbee8)
[Git Repo](https://github.com/robbert229/aurelia-router-bug)

## Reproduction Instructions

1. Click on `Documents`
2. Click on `Link`
3. Click on `Broken Edit` and notice how it navigates to edit. 
4. Click on `Broken Details` and notice how it navigates to details.
5. Reload the page.
6. Click `Broken Edit`, it shouldn't navigate away from `Edit`. 
7. Click `Edit`
8. Click on `Broken Details`, it shouldn't navigate to details either. 

```
aurelia.js:14793 ERROR [app-router] Error: Route not found: /details
        at AppRouter._createNavigationInstruction (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:16353:29)
        at AppRouter.loadUrl (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:16948:19)
        at BrowserHistory._loadUrl (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:14456:55)
        at BrowserHistory._checkUrl (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:14449:14)error @ aurelia.js:14793
    aurelia.js:14793 ERROR [app-router] Error: Route not found: /edit
        at AppRouter._createNavigationInstruction (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:16353:29)
        at AppRouter.loadUrl (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:16948:19)
        at BrowserHistory._loadUrl (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:14456:55)
        at BrowserHistory._checkUrl (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:14449:14)
```
![Demo](https://github.com/robbert229/aurelia-router-bug/raw/master/tldr.gif)

* **What is the expected behavior?**
The expected behavior is that refreshing a page on a child router should not effect the route's from being found.

* **What is the motivation / use case for changing the behavior?**
This doesn't make sense..

**Comment by robbert229** [comment]
This is actually a repeat of #306
