### ISSUE TITLE
Unknown route handler not handling unknown routes.

### ISSUE THREAD

**Issue by don-bluelinegrid** [aurelia/router#498]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
6.9.4

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
webpack 2.2.1

* **Browser:**
all 

* **Language:**
TypeScript X.X

**Current behavior:**

When programmatically navigating to a route that should be unknown and should redirect to a default route, an exception is thrown:
```
bluebird.js:1542 Unhandled rejection Error: A route with name '' could not be found. Check that `name: ''` was specified in the route's config.
    at AppRouter.generate (http://localhost:9000/aurelia.bundle.js:15602:13)
    at AppRouter.navigateToRoute (http://localhost:9000/aurelia.bundle.js:15578:21)
    at http://localhost:9000/app.bundle.js:66743:27
From previous event:
    at http://localhost:9000/app.bundle.js:66741:30
    at invokeCallback (http://localhost:9000/aurelia.bundle.js:12843:5)
    at EventAggregator.publish (http://localhost:9000/aurelia.bundle.js:12880:11)
    at http://localhost:9000/app.bundle.js:88745:48
From previous event:
    at Login._callee$ (http://localhost:9000/app.bundle.js:88732:78)
    at tryCatch (http://localhost:9000/app.bundle.js:49577:40)
    at Generator.invoke [as _invoke] (http://localhost:9000/app.bundle.js:49812:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:9000/app.bundle.js:49629:21)
    at http://localhost:9000/app.bundle.js:88654:71
From previous event:
    at __awaiter (http://localhost:9000/app.bundle.js:88634:12)
    at Login.login (http://localhost:9000/app.bundle.js:88720:16)
    at CallScope.evaluate (http://localhost:9000/aurelia.bundle.js:6432:19)
    at Conditional.evaluate (http://localhost:9000/aurelia.bundle.js:6236:82)
    at Listener.callSource (http://localhost:9000/aurelia.bundle.js:9995:40)
    at http://localhost:9000/aurelia.bundle.js:10019:22
    at HTMLDocument.handleDelegatedEvent (http://localhost:9000/aurelia.bundle.js:8140:9)
```
This occurs when I provide either `''` or `'/'` as the navigation target.

**Expected/desired behavior:**
If a route is not found, and if there is an unknown route handler defined with `routeConfig.mapUnknownRoutes()`, then the unknwon route should be handled - an exception should not be thrown.

* **What is the expected behavior?**

I do have such an unknown route handler defined:

```
    config.mapUnknownRoutes((instruction: NavigationInstruction) => {
      let user = me.session.auth['member'];
      let route = './community';
      if (user && !!(me.session.getRole())) {
        if (me.session.getRole() === 'admin') {
          route = './organization/organization';
        }
      }
      return route;
    });

```
However, I am seeing the exception noted above.

* **What is the motivation / use case for changing the behavior?**
We need to be able to navigate to an arbitrarily-defined 'default' route.

**Comment by davismj** [comment]
You're calling `router.navigateToRoute('')`. You need to be calling `router.navigate('')`. `navigateToRoute(routeName)` takes the name route, as specified in the `name` property of the route config. `navigate(fragment)` takes a url as a string and determines the matching route from it.
