### ISSUE TITLE
redirect route doesn't work.

### ISSUE THREAD

**Issue by Zoltu** [aurelia/router#63]
In the previous version of Aurelia I was able to do
```
{ route: '', redirect: 'about' },
```
After updating, that not only doesn't redirect, but it causes my router to fail to initialize, taking down my entire application.
```
Uncaught Error: Error instantiating App.
------------------------------------------------
inner error: Error: Invalid route config.
    at validateRouteConfig (http://localhost:9000/jspm_packages/github/aurelia/router@0.7.1/router.js:9:13)
    at AppRouter.addRoute (http://localhost:9000/jspm_packages/github/aurelia/router@0.7.1/router.js:220:13)
    at RouterConfiguration.configureRoute (http://localhost:9000/jspm_packages/github/aurelia/router@0.7.1/router-configuration.js:142:20)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/router@0.7.1/router-configuration.js:88:23)
    at RouterConfiguration.exportToRouter (http://localhost:9000/jspm_packages/github/aurelia/router@0.7.1/router-configuration.js:110:30)
    at AppRouter.configure (http://localhost:9000/jspm_packages/github/aurelia/router@0.7.1/router.js:99:22)
    at new App (http://localhost:9000/output/app.js:26:18)
    at Object.reflect.construct (http://localhost:9000/jspm_packages/github/zloirock/core-js@0.8.1/modules/es6.reflect.js:81:26)
    at ClassActivator.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.6.0/metadata.js:259:28)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.6.0/container.js:211:37)
```

```
"aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.11.0",
"aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.6.0",
"aurelia-framework": "github:aurelia/framework@^0.10.0",
"aurelia-http-client": "github:aurelia/http-client@^0.7.0",
"aurelia-router": "github:aurelia/router@^0.7.1",
```

**Comment by EisenbergEffect** [comment]
Got it. Going out in the next release.
